using Gedaq.Common.Enums;
using System;

namespace Gedaq.SqlClient.Attributes
{
    /// <summary>
    /// Attribute for generating a database query method
    /// </summary>
    /// <seealso href="https://github.com/SoftStoneDevelop/Gedaq.SqlClient/blob/main/Documentation/Query.md"/>
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Method, AllowMultiple = true)]
    public sealed class QueryAttribute : Attribute
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="methodName">Name of the generated method</param>
        /// <param name="query">Sql query</param>
        /// <param name="queryMapTypes">The types into which the string received from the database will be converted</param>
        /// <param name="overrideAliasPrefixs">Alias ​​overrides that are derived from attributes <seealso cref="Gedaq.Common.Attributes.AliasAttribute"/></param>
        /// <param name="methodType">Type of generated method see <see cref="MethodType"/></param>
        /// <param name="queryType">The type of query used/generated see <see cref="QueryType"/></param>
        /// <param name="generate">The need to generate a method. In case requests are used only as part of a batch, it may not be necessary to generate single methods for a request.</param>
        /// <param name="accessModifier">Access Modifier of Generated Methods see <see cref="AccessModifier"/></param>
        /// <param name="asyncResultType">The type of the generated Task/ValueTask see <see cref="AsyncResult"/> method</param>
        /// <param name="asPartInterface">The interface of which the generated method should be a part. It also generates descriptions of this method for the interface.</param>
        /// <param name="returnType">The type of the return collection that will be generated by the method. See <see cref="ReturnType"/></param>
        public QueryAttribute(
            string methodName,
            string? query = null,
            Type[]? queryMapTypes = null,
            string[]? overrideAliasPrefixs = null,
            MethodType methodType = MethodType.Sync,
            QueryType queryType = QueryType.Read,
            bool generate = true,
            AccessModifier accessModifier = AccessModifier.AsContainingClass,
            AsyncResult asyncResultType = AsyncResult.ValueTask,
            Type? asPartInterface = null,
            ReturnType returnType = ReturnType.List)
        {
        }
    }
}